heat_template_version: newton

description: Template that assigns a floating IP address to a server.

parameters:
  port:
    type: string
    label: Server port
    description: The server port that receives the floating IP address.

  fixed_private_ip:
    type: string
    label: Server Private IP
    description: The server private IP that receives the floating IP address.
    
  public_net:
    type: string
    label: Public network name or ID
    description: Public network with floating IP addresses.
    default: public-971

resources:
  floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: { get_param: public_net }

  floating_ip_assoc:
    type: OS::Neutron::FloatingIPAssociation
    properties:
      floatingip_id: { get_resource: floating_ip }
      port_id: { get_param: port }
      fixed_ip_address: { get_param: fixed_private_ip }

outputs:
  ip:
    description: The floating IP address assigned to the server.
    value: { get_attr: [floating_ip, floating_ip_address] }
