heat_template_version: newton

description: Template that creates a private network.

parameters:
  public_net:
    type: string
    label: Public network name or ID
    description: Public network with floating IP addresses.
    default: WSU_Public_971
  private_net_name:
    type: string
    description: Private network name
    default: test_net
  private_net_cidr:
    type: string
    label: CIDR
    description: Classless Inter-Domain Routing (CIDR) of the private network.
    default: '10.10.11.0/24'
  private_net_gateway:
    type: string
    description: Private network gateway address
    default: '10.10.11.1'
  dns:
    type: comma_delimited_list
    label: DNS nameservers
    description: Comma separated list of DNS nameservers for the private network.
    default: '156.26.250.22,156.26.10.21,156.26.1.1'

  # allocation_pools not defined but available for future templates
  # private_net_pool_start:
  #   type: string
  #   description: Start of private network IP address allocation pool
  # private_net_pool_end:
  #   type: string
  #   description: End of private network IP address allocation pool

resources:
  private_net:
    type: OS::Neutron::Net
    properties:
      name: { get_param: private_net_name }

  private_subnet:
    type: OS::Neutron::Subnet
    properties:
      name: { str_replace: { params: { __name_prefix__: { get_param: private_net_name } }, template: __name_prefix__-sub } }
      network_id: { get_resource: private_net }
      cidr: { get_param: private_net_cidr }
      gateway_ip: { get_param: private_net_gateway }
      dns_nameservers: { get_param: dns }

      # allocation_pools not defined but available for future templates
      # allocation_pools:
      #   - start: { get_param: private_net_pool_start }
      #     end: { get_param: private_net_pool_end }

  router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info:
        network: { get_param: public_net }

  router-interface:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: router }
      subnet: { get_resource: private_subnet }

outputs:
  net_name:
    description: The private network name.
    value: { get_attr: [private_net, name] }
  subnet_name:
    description: The private subnet name.
    value: { get_attr: [private_subnet, name] }
  cidr:
    description: The private subnet cidr.
    value: { get_attr: [private_subnet, cidr] }
