heat_template_version: newton

description: Template to create security groups for cluster

## DEFINE PARAMS OR PULL IN FROM UPSTREAM TEMPLATE
parameters:
  cluster_access:
    type: string
    label: cluster network access
    description: network access into cluster via bastion or gateway.
    default: wsu_only

  private_subnet_cidr:
    type: string
    label: private cidr
    description: Subnet cidr to scope down security groups to private tenant network.
    default: 10.10.11.0/24

  wsu_publicnet_cidr:
    type: string
    label: wsu public cidr
    description: Subnet cidr to scope down security groups to wsu public network.
    default: 156.26.0.0/16

  wsu_vpnnet_cidr:
    type: string
    label: wsu vpn cidr
    description: Subnet cidr to scope down security groups to wsu private vpn network.
    default: 10.250.0.0/24

  datacenter_net_cidr:
    type: string
    label: datacenter cidr
    description: Subnet cidr to scope down security groups to wsu datacenter internal network.
    default: 192.168.250.0/24

conditions:
  external_access:
    equals:
      - get_param: cluster_access
      - external_access

  wsu_access:
    equals:
     - get_param: cluster_access
     - wsu_only

  datacenter_access:
    equals:
     - get_param: cluster_access
     - datacenter_only

  prinet_access:
    equals:
     - get_param: cluster_access
     - prinet_only

resources: 

## DEFINE CLUSTER SECURITY GROUPS
  sg_ingress_ssh_prinet:
      type: OS::Neutron::SecurityGroup
      properties:
        name: ingress_ssh_ping_private_subnet
        description: SSH and PING ingress from private network only
        rules:
          - remote_ip_prefix: { get_param: private_subnet_cidr }
            protocol: icmp
          - remote_ip_prefix: { get_param: private_subnet_cidr }
            protocol: tcp
            port_range_min: 22
            port_range_max: 22

  sg_ingress_ping:
      type: OS::Neutron::SecurityGroup
      properties:
        name: ingress_ping_wsu_public_net
        description: PING ingress from private subnet and WSU public network only
        rules:
          - remote_ip_prefix: { get_param: private_subnet_cidr }
            protocol: icmp
          - remote_ip_prefix: { get_param: wsu_publicnet_cidr }
            protocol: icmp

  sg_ingress_ssh_external:
      type: OS::Neutron::SecurityGroup
      condition: external_access
      properties:
        name: ingress_ssh_wide_open
        description: SSH ingress from ANY network
        rules:
          - protocol: tcp
            port_range_min: 22
            port_range_max: 22

  sg_ingress_ssh_wsu:
      type: OS::Neutron::SecurityGroup
      condition: wsu_access
      properties:
        name: ingress_ssh_wsu_net
        description: SSH ingress from WSU public network only
        rules:
          - remote_ip_prefix: { get_param: wsu_publicnet_cidr }
            protocol: tcp
            port_range_min: 22
            port_range_max: 22
          - remote_ip_prefix: { get_param: wsu_vpnnet_cidr }
            protocol: tcp
            port_range_min: 22
            port_range_max: 22

## DEFINE OUTPUTS TO UPSTREAM TEMPLATE
outputs:
  sg_ingress_ping:
    description: PING ingress from WSU public network
    value: { get_resource: sg_ingress_ping }
  sg_ingress_ssh_prinet:
    description: SSH and PING ingress from private network only
    value: { get_resource: sg_ingress_ssh_prinet }
  sg_ingress_ssh:
    description: SSH ingress from defined external network
    value: { if: [external_access, {get_resource: sg_ingress_ssh_external}, {get_resource: sg_ingress_ssh_wsu}] }
