heat_template_version: 2013-05-23
 
description: Template for setting up a private network and running a server
 
parameters:
  image:
    type: string
    label: Image name or ID
    description: Image to be used for server. Please use an Ubuntu based image.
    default: rhel-73-cloudimg
  flavor:
    type: string
    label: Flavor
    description: Type of instance (flavor) to be used on the compute instance.
    default: m1.small
  key:
    type: string
    label: Key name
    description: Name of key-pair to be installed on the compute instance.
    default: test
  public_net:
    type: string
    label: Public network name or ID
    description: Public network to attach server to.
    default: public-971
 
resources:

  network:
    type: lib/private_network.yaml
    properties:
      public_net: { get_param: public_net }

  debian_instance:
    type: lib/debian_vm2.yaml
    properties:
      image: { get_param: image }
      flavor: { get_param: flavor }
      key: { get_param: key }
      private_net: { get_attr: [network, name] }

  floating_ip:
    type: lib/floating_ip.yaml
    properties:
      port: { get_attr: [debian_instance, port] }
      public_net: { get_param: public_net }

outputs:
  ip:
    description: The public IP address to access debian_box.
    value: { get_attr: [floating_ip, ip] }
